site:
  title: KBT-Documentation
  # the 404 page and sitemap files only get generated when the url property is set
  #url: https://antora.demo.com/demo/docs-site
  start_page: Documentation::index.adoc
content:
  sources:
    - url: https://gitlab.com/merco_ecosystem/kb_playground.git 
      branches: feature/#95/manu 
      start_path: docs
      

asciidoc:
  attributes:
    experimental: true
    idprefix: custom-prefix
    idseparator: '-'
    page-pagination: simple
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/prod-166/ui-bundle.zip #https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output: 
  clean: true 
  dir: ./public
 




